#!/bin/sh
# Pre-commit hook to run gofmt on Go files

files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')

if [ -n "$files" ]; then
    unformatted=$(echo "$files" | xargs gofmt -l)
    
    if [ -n "$unformatted" ]; then
        echo "以下のファイルがgofmtのフォーマットに準拠していませんでした:"
        echo "$unformatted"
        echo ""
        gofmt -w $unformatted
        git add $unformatted
        echo "フォーマットが完了したので再度commitしてください"
        exit 1
    fi
fi

exit 0